---
title: "Case Study 05"
author: Your Name
date: August 1, 2020
output: github_document
---
library(spData)
library(sf)
library(tidyverse)
library(units)

#Load world data from sp package and states boundries from sf, use library(units) to make conversions easier
data(world)
data(us_states)
library(units)

#transform to albers coordinate projection
albers="+proj=aea +lat_1=29.5 +lat_2=45.5 +lat_0=37.5 +lon_0=-96 +x_0=0 +y_0=0 +ellps=GRS80 +datum=NAD83 +units=m +no_defs"

#filter world dataset to include only name_long=="Canada"

canbuffer <- world %>%
  st_transform(crs=albers)%>% 
  filter(name_long=='Canada')%>%  #buffer canada to 10000m
  st_buffer(dist=10000)

#transform to albers and filter to include only new york
NY <- us_states%>%
  st_transform(crs=albers)%>% 
  filter(NAME=="New York") 

#plot(NY)

#Create Border object
Borderobj <- st_intersection(canbuffer,NY)

Bordercs5 <- NY %>% ggplot() +
  geom_sf() +  
  geom_sf(data = Borderobj, fill = "red") +  
  ggtitle("New York Land within 10km") +  
  theme(plot.title = element_text(hjust = 0.5))  

plot(Bordercs5)

st_area(Borderobj)


ConvArea <- Borderobj %>%st_area()%>% 
  set_units("km^2") 
ConvArea